priv_key_file: /key
peer_type: provider
p2p_port: 13522
http_port: 13523
rpc_port: 13524
secret: hello
log_fmt: text
log_level: debug
expose_provider_api: true
preconf_contract: 0xD11e7E017e22232912E2F8150751436c4E6ec606
provider_registry_contract: 0x11a315df6B4aCDbB6816B287a10F92F0C3a1BBc1
user_registry_contract: 0x17855D7AB9B84cF2eddb8a7Db2df825c54a492aD
rpc_endpoint: http://34.215.163.180:8545
bootnodes:
  - /ip4/172.28.0.2/tcp/13522/p2p/16Uiu2HAmLYUvthfDCewNMdfPhrVefBbsfaPL22fWWfC2zuoh5SpV
