priv_key_file: /keys/provider
peer_type: provider
p2p_port: 13522
http_port: 13523
rpc_port: 13524
secret: hello
log_fmt: text
log_level: debug
expose_provider_api: true
bootnodes:
  - /ip4/<localhost>/tcp/13522/p2p/<p2p_ID>
